<?php $data=$this->getDataById() ?>
<form action="<?php echo $this->getUrl('company_details/index/save').'id/'.$data->getId(); ?>" method="post">
    <label for="company_name">Company Name</label>
    <input type="text" name="company_name" id="company_name" value="<?php echo $data->getCompanyName() ?>"/>
    <label for="annual_income">Annual Income</label>
    <input type="text" name="annual_income" id="annual_income" value="<?php echo $data->getAnnualIncome() ?>"/>
    <label for="address">Address</label>
    <input type="text" name="address" id="address" value="<?php echo $data->getAddress() ?>">
    <label for="work_time_start">Work Time Start</label>
    <input type="text" name="work_time_start" id="work_time_start" value="<?php echo $data->getWorkTimeStart() ?>" />
    <label for="work_time_end">Work Time End</label>
    <input type="text" name="work_time_end" id="work_time_end" value="<?php echo $data->getWorkTimeEnd() ?>"/>
    <label for="total_employees">Total Employees</label>
    <input type="text" name="total_employees" id="total_employees" value="<?php echo $data->getTotalEmployees() ?>"/>
    <button type="submit">Update</button>
</form>
